name: chats
description: "A new Flutter project."

publish_to: "none"
version: 2.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.2.1
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^18.0.1
  get: ^4.6.6
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  easy_refresh: ^3.4.0
  calendar_date_picker2: ^1.1.8
  toastification: ^2.3.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  zoom_tap_animation: ^1.1.0
  pin_code_fields: ^8.0.1
  phone_number: ^2.1.0
  chewie: 1.7.4
  video_player: ^2.9.2
  flutter_file_downloader: ^2.0.0
  url_launcher: ^6.3.1
  contacts_service: ^0.6.3
  permission_handler: ^11.3.1
  pusher_channels_flutter: 2.2.1
  shimmer_animation:
    git:
      url: https://github.com/Levanmanh2002/shimmer_animation.git
      ref: master
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  scrollable_positioned_list: ^0.3.8
  agora_rtc_engine: ^6.5.0
  flutter_callkit_incoming: ^2.5.0
  flutter_ringtone_player: ^4.0.0+4
  path_provider: ^2.1.5
  flutter_html: ^3.0.0-beta.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/audios/
    - .env

  fonts:
    - family: SemiBold
      fonts:
        - asset: assets/fonts/SVN-Poppins-SemiBold.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/SVN-Poppins-Regular.ttf
